add oci annotations

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -87,15 +87,21 @@ jobs:
               break
             fi
 
-            PUSH_STDOUT=$(helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts")
+            if ! PUSH_STDOUT=$(helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts" 2>&1); then
+              echo $PUSH_STDOUT
+
+              echo "Failed to push ${pkg}"
+              exit 1
+            fi
+
             echo $PUSH_STDOUT
             TAG="$(echo "$PUSH_STDOUT" | head -n 1 | cut -d: -f2- | tr -d ' ')"
 
             CHART_NAME="$(echo "${pkg##*/}" | cut -d- -f 1)"
 
-            echo Annnotating image with OCI labels
+            echo "Annnotating image tag $TAG with OCI labels"
 
-            echo docker buildx imagetools create \
+            docker buildx imagetools create \
               --annotation "index:org.opencontainers.image.authors=Jan-Otto Kröpke" \
               --annotation "index:org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
               --annotation "index:org.opencontainers.image.licenses=Apache-2.0" \
